name: tangullo
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.3 <4.0.0' # Change to '^3.5.0' if necessary

dependencies:
  flutter:
    sdk: flutter
  stacked: ^3.4.0
  stacked_services: ^1.1.0
  animated_splash_screen: ^1.3.0
  animated_bottom_navigation_bar: ^1.3.3
  lottie: ^3.1.2
  convex_bottom_bar: ^3.0.0
  curved_navigation_bar: ^1.0.6
  flutter_expandable_fab: ^2.2.0
  floating_action_wheel: ^1.0.1
  firebase_core: ^3.4.0
  firebase_auth: ^5.2.0
  logger: ^2.4.0
  shared_preferences: ^2.3.2
  cloud_firestore: ^5.4.0
  sliding_clipped_nav_bar: ^3.1.1
  awesome_drawer_bar: ^1.2.0
  tale_drawer: ^0.0.1
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.10+1
  audioplayers: ^6.1.0
  http: ^1.2.2
  syncfusion_flutter_charts: ^27.1.51
  percent_indicator: ^4.2.3
  url_launcher: ^6.3.0
  flutter_staggered_grid_view: ^0.7.0
  badges: ^3.1.2
  video_player: ^2.3.0 
  table_calendar: ^3.1.2
  in_app_review: ^2.0.9
  youtube_player_flutter: ^9.1.1
  webview_flutter: ^4.10.0
  firebase_database: ^11.1.4
  flutter_map: ^7.0.2
  image_picker: ^1.1.2
  firebase_storage: ^12.3.3
  fl_chart: ^0.69.0
  line_awesome_flutter: ^3.0.1
  flutter_zoom_drawer: ^3.2.0
  dio: ^5.7.0
  dio_cache_interceptor: ^3.5.0
  just_audio: ^0.9.42
  audio_service: ^0.18.15
  cached_network_image: ^3.4.1
  shimmer: ^3.0.0
  
  
 
  
  
 
  
  
 










dev_dependencies:
  build_runner: ^2.4.5
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mockito: ^5.4.1
  stacked_generator: ^1.3.3



flutter:
  assets:
    - assets/animation.json
    - assets/tink.png
    - assets/robot.jpg
    - assets/user.jpg
    - assets/icons/facebook.png
    - assets/icons/instagram.png
    - assets/icons/pinterest.png
    - assets/icons/linkedin.png
    - assets/icons/fingerprint.png
    - assets/icons/image11.png
    - assets/mental.png
    - assets/background.jpg
    - assets/profiles.jfif
    - assets/photo.jfif
    - assets/johnchris.jpg
    - assets/shaira.jpg
    - assets/alvin.jpg
    - assets/cristine.jpg
    - assets/renvir.jpg
    - assets/rocky.jpg
    - assets/edison.jpg
    - assets/user_1.jpg
    - assets/tae/hamburger.svg
    - assets/images/user.jpg
    - assets/images/happy.png
    - assets/images/calm.png
    - assets/images/relax.png
    - assets/images/focus.png
    - assets/images/meetup.png
    - assets/images/meditation.png
    - assets/img/
    - assets/images/
    - assets/tae/
    - assets/meditation/
    - assets/bg_home_border.svg
    - assets/bg_moon_home.svg
    - assets/loading_animation.json
    - assets/chatbot/kb.json
    - assets/kb.json
    - assets/loading/thinking.json
    - assets/loading/tink.json
    - assets/loading/chatbot.json
    - assets/Meditation_avatar.png
    - assets/test.jpg
    - assets/meditatee.png
    - assets/videos/session1.mp4
    - assets/meditation/breathe.png
    - assets/images/calm1.jpg
    - assets/images/calm2.jpg
    - assets/images/calm3.jpg
    - assets/images/calm4.jpg
    - images/
    - assets/loading/splash.json
    
    
    
    
    
    
  

   

  uses-material-design: true
