name: tangullo
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.3 <4.0.0' # Change to '^3.5.0' if necessary

dependencies:
  flutter:
    sdk: flutter
  stacked: ^3.4.0
  stacked_services: ^1.1.0
  animated_splash_screen: ^1.3.0
  animated_bottom_navigation_bar: ^1.3.3
  lottie: ^3.1.2
  convex_bottom_bar: ^3.0.0
  curved_navigation_bar: ^1.0.6
  flutter_expandable_fab: ^2.2.0
  floating_action_wheel: ^1.0.1
  firebase_core: ^3.4.0
  firebase_auth: ^5.2.0
  logger: ^2.4.0
  shared_preferences: ^2.3.2
  cloud_firestore: ^5.4.0
  sliding_clipped_nav_bar: ^3.1.1
  awesome_drawer_bar: ^1.2.0
  tale_drawer: ^0.0.1
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.10+1
  audioplayers: ^6.1.0
  http: ^1.2.2
  syncfusion_flutter_charts: ^27.1.51
  percent_indicator: ^4.2.3
  url_launcher: ^6.3.0
  flutter_staggered_grid_view: ^0.7.0
  badges: ^3.1.2
  video_player: ^2.3.0 
  table_calendar: ^3.1.2
  in_app_review: ^2.0.9
  youtube_player_flutter: ^9.1.1
  webview_flutter: ^4.0.0
  firebase_database: ^11.1.4
  flutter_map: ^7.0.2
  image_picker: ^1.1.2
  firebase_storage: ^12.3.3
  fl_chart: ^0.69.0
  line_awesome_flutter: ^3.0.1
  flutter_zoom_drawer: ^3.2.0
  dio: ^5.7.0
  dio_cache_interceptor: ^3.5.0
  just_audio: ^0.9.42
  audio_service: ^0.18.15
  cached_network_image: ^3.4.1
  shimmer: ^3.0.0
  auto_size_text: ^3.0.0
  flutter_launcher_icons: ^0.14.3
  flutter_spinkit: ^5.2.1
  spotify_sdk: ^3.0.2
  flutter_animate: ^4.5.2
  fluttertoast: ^8.2.12
  font_awesome_flutter: ^10.8.0
  hexcolor: ^3.0.1
  agora_rtc_engine: ^6.5.1
  permission_handler: ^11.4.0
  flutter_dotenv: ^5.2.1
  liquid_progress_indicator_v2: ^0.5.0
  carousel_slider: ^5.0.0
  animated_toggle_switch: ^0.8.4
  simple_animation_progress_bar: ^1.8.2
  proximity_sensor: ^1.3.8
  sensors_plus: ^6.1.1
  pedometer: ^4.0.2
  tflite_flutter: ^0.11.0
  camera: ^0.11.0+2
  
  
  
  
 
  
  
 
  
  
 










dev_dependencies:
  build_runner: ^2.4.5
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mockito: ^5.4.1
  stacked_generator: ^1.3.3



flutter:
  assets:
    - assets/animation.json
    - assets/tink.png
    - assets/robot.jpg
    - assets/user.jpg
    - assets/icons/
    - assets/mental.png
    - assets/background.jpg
    - assets/profiles.jfif
    - assets/photo.jfif
  
    - assets/user_1.jpg
    - assets/tae/hamburger.svg
    - assets/images21/user.jpg
    - assets/images21/happy.png
    - assets/images21/calm.png
    - assets/images21/relax.png
    - assets/images21/focus.png
    - assets/images21/meetup.png
    - assets/images21/meditation.png
    - assets/img/
    - assets/images21/
    - assets/tae/
    - assets/meditation/
    - assets/bg_home_border.svg
    - assets/bg_moon_home.svg
    - assets/loading_animation.json
    - assets/chatbot/kb.json
    - assets/kb.json
    - assets/loading/thinking.json
    - assets/loading/tink.json
    - assets/loading/chatbot.json
    - assets/Meditation_avatar.png
    - assets/test.jpg
    - assets/meditatee.png
    - assets/videos/session1.mp4
    - assets/meditation/breathe.png
    - assets/images21/calm1.jpg
    - assets/images21/calm2.jpg
    - assets/images21/calm3.jpg
    - assets/images21/calm4.jpg
    - assets/icons/news.png
    - images/
    - assets/images21/logs.png
    - assets/loading/splash.json
    - assets/images21/music.png
    - assets/images/sign-in.png
    - assets/icons_/
    - assets/icons_/icons/bg.svg
    - assets/icons_/icons/clock.svg
    - assets/icons_/icons/K10_survey.jpg
    - assets/images/detail_illustration.png
    - assets/images/doctor1.png
    - assets/images/doctor2.png
    - assets/images/doctor3.png
    - assets/images/onboarding_illustration.png
    - assets/icons_/icons/psychiatrist.png
    - assets/images/mentalHealth.png
    - assets/images/google-logo.png
    - assets/images/ReliveLogo.png
    - assets/images/GetStarted.png
    - assets/settings.png
    - assets/appointment.png
    - assets/patient.png
    - assets/available.png
    - assets/interaction.png
    - assets/report.png
    - assets/fitness_app/
    - assets/images/
    - assets/images/yoga1.jpg
    - assets/images/yoga2.jpg
    - assets/images/yoga3.jpg
    - assets/images/yoga4.jpg
    - assets/tflite_for_live/model.tflite
    - assets/tflite_for_live/labels.txt
    - assets/hehe.gif
    
    


  uses-material-design: true
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/play_store_512.png" # Include the `.png` extension
  min_sdk_android: 21
